
server:
  port: 8088
#  servlet:
#    context-path: /client1

#配置安全相关模块
security:
  oauth2:
    client:
      client-id: cus1
      client-secret: cus1
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html