server:
  port: 8090

spring:
  security:
    oauth2:
      client:
        registration: #是OAuth客户端所有属性的基础前缀
          authorizationserver:
            client-id: client-for-server
            client-secret: client-for-server
            provider: authorizationserver
            client-name: 使用自定义授权服务器登录
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            scope: all
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          authorizationserver:
            authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
            token-uri: http://127.0.0.1:9999/server/oauth/token
            user-info-uri: http://127.0.0.1:9999/server/me
            user-name-attribute: "name"