server:
  port: 9999
  servlet:
    context-path: /server
spring:
  security:
    user:
      name: test
      password: 1234

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.security: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG


